### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by alexbue** [YahiaAngelo/MaterialMapGenerator#4]
> Python: Traceback (most recent call last):
>   File "C:\Users\alxbu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\MaterialMapGenerator\__init__.py", line 86, in execute
>     main(self, context)
>   File "C:\Users\alxbu\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\MaterialMapGenerator\__init__.py", line 43, in main
>     shutil.copy2(node_active.image.filepath, absolute_path("input"))
>   File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 434, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\shutil.py", line 254, in copyfile
>     with open(src, 'rb') as fsrc:
> FileNotFoundError: [Errno 2] No such file or directory: '//Griff-Oberseite-Spanner.002.png'

I dont know why, but my paths are not valid for some reason. Could this be a problem of the corresponding python-version?

**Comment by YahiaAngelo** [comment]
@alexbue I've seen this issue happen with a couple of other users, but I can't figure out when it happens exactly.
So can you please share more info about your environment?
And does it always happen or it just happens sometimes?

**Comment by Kahnetop** [comment]
@YahiaAngelo 

im on the last version of blender (3.3) and also got it and it happens everytimes, i don't know enough of how python blender to know why so here is all messages/logs i got 
![image](https://user-images.githubusercontent.com/115363378/205504697-e377ab0f-7a3b-4dfc-b526-539d8929d6ac.png)
![image](https://user-images.githubusercontent.com/115363378/205504903-13f1d8f9-564e-4b16-84f0-be00c859a865.png)

**Comment by YahiaAngelo** [comment]
@Kahnetop, @alexbue  Please download the [fix-images-path](https://github.com/YahiaAngelo/MaterialMapGenerator/tree/fix-images-path) branch and try it out.
